version: "3"
services:
  mysql:
    image: mysql:8.0.25
    platform: linux/amd64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: JNASlsa!k123en
      MYSQL_DATABASE: golang-demo
      MYSQL_USER: thanhle
      MYSQL_PASSWORD: 123456
      LANG: C.UTF-8
    ports:
      - 3307:3306
    volumes:
      - .docker/mysql/data/:/var/lib/mysql
      - .docker/mysql/log/:/var/log/mysql
